export const EVENTS = {
  REGISTER: "REGISTER",

  SEND_MESSAGE: "SEND_MESSAGE",

  SERVER_ACK: "SERVER_ACK",

  DELIVERED_ACK: "DELIVERED_ACK",

  READ_MESSAGE: "READ_MESSAGE",

  READ_ACK: "READ_ACK",
};